### ISSUE TITLE
Discord Freezes my Chromebook

### ISSUE THREAD

**Issue by justincodingprojects** [binary-person/rammerhead#11]
When I tried to go to discord.com/app or discord.gg and log in (i used qr code to log in), once it reached the main page, it freezes up my chromebook. Either I has to force restart it, or wait for chrome os to crash.

**Comment by binary-person** [comment]
is this happening to the open source version?

**Comment by justincodingprojects** [comment]
Well, Idk because when I was on my Chromebook, using the rammerhead browser, want to go to discord, it freezes is my Chromebook. But if it is on my desktop computer, it doesn't freeze, and it works all fine come up with a little bit of lag. I haven't tried using the open source version yet though..

**Comment by zdc54** [comment]
im not binary-person, but im assuming that this github issues page is for issues related to the open source version of rammerhead, not the browser version.

**Comment by justincodingprojects** [comment]
Oh, okay 🙂

**Comment by binary-person** [comment]
you may be right about that, but since the browser version uses this package as its fundamental core, problems that arise from the browser version usually also arise in this, so it's totally ok to open an issue experienced in the browser.

like for example, the crashing problem has been solved with [this commit](https://github.com/binary-person/rammerhead/commit/d04e0e931802e5eeea32aa4d541706dee9c899fd)

**Comment by justincodingprojects** [comment]
That's Ok 🙂
